#include <regs_16.h>
// Definições para o PIC12F629 e 12F675
// Autor: Fábio Pereira
#BYTE GPIO		= 0x05
// PIR1
	#BIT EEIF	= PIR1.7
	#BIT ADIF	= PIR1.6
	#BIT CMIF	= PIR1.3
	#BIT TMR1IF	= PIR1.0
// TIMER1
	#BIT TMR1GE	= T1CON.6
#BYTE CMCON		= 0x19
	#BIT COUT	= CMCON.6
	#BIT CINV	= CMCON.4
	#BIT CIS	= CMCON.3
	#BIT CM2	= CMCON.2
	#BIT CM1	= CMCON.1
	#BIT CM0	= CMCON.0
#BYTE ADRESH		= 0x1E
#BYTE ADCON0		= 0x1F
	#BIT ADFM	= ADCON0.7
	#BIT VCFG	= ADCON0.6
	#BIT CHS1	= ADCON0.3
	#BIT CHS0	= ADCON0.2
	#BIT GO_DONE	= ADCON0.1
	#BIT ADON	= ADCON0.0
// OPTION_REG
	#BIT GPPU	= OPTION.7
#BYTE TRISIO		= 0x85
// INTCON
	#BIT GPIE	= INTCON.3
	#BIT GPIF	= INTCON.0
// PIE1
	#BIT EEIE	= PIE1.7
	#BIT ADIE	= PIE1.6
	#BIT CMIE	= PIE1.3
	#BIT TMR1IE	= PIE1.0
#BYTE VRCON		= 0x99
	#BIT VREN	= VRCON.7
	#BIT VRR	= VRCON.5
	#BIT VR3	= VRCON.3
	#BIT VR2	= VRCON.2
	#BIT VR1	= VRCON.1
	#BIT VR0	= VRCON.0
#BYTE EEDATA		= 0x9A
#BYTE EEADR		= 0x9B
#BYTE EECON1		= 0x9C
	#BIT WRERR	= EECON1.3
	#BIT WREN	= EECON1.2
	#BIT WR		= EECON1.1
	#BIT RD		= EECON1.0
#BYTE EECON2		= 0x9D
#BYTE ADRESL		= 0x9E
#BYTE ANSEL		= 0x9F
	#BIT ADCS2	= ANSEL.6
	#BIT ADCS1	= ANSEL.5
	#BIT ADCS0	= ANSEL.4
	#BIT ANS3	= ANSEL.3
	#BIT ANS2	= ANSEL.2
	#BIT ANS1	= ANSEL.1
	#BIT ANS0	= ANSEL.0

